import os
import datetime
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from dotenv import load_dotenv

load_dotenv()

SCOPES = ['https://www.googleapis.com/auth/calendar']

def get_calendar_service():
    """Gets Google Calendar API service using Service Account or OAuth2 token."""
    # Method 1: Service Account (Highly recommended for servers like Render)
    service_account_file = 'service_account.json'
    if os.path.exists(service_account_file):
        try:
            creds = service_account.Credentials.from_service_account_file(
                service_account_file, scopes=SCOPES)
            return build('calendar', 'v3', credentials=creds)
        except Exception as e:
            print(f"[警告] 讀取服務帳戶金鑰 (service_account.json) 失敗: {e}")

    # Method 2: OAuth2 token.json (Generated by running auth_google.py locally)
    creds = None
    if os.path.exists('token.json'):
        try:
            creds = Credentials.from_authorized_user_file('token.json', SCOPES)
        except Exception as e:
            print(f"[警告] 讀取 token.json 失敗: {e}")
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
                with open('token.json', 'w') as token:
                    token.write(creds.to_json())
            except Exception as e:
                print(f"[警告] 刷新 Google Token 失敗: {e}")
                creds = None
        else:
            creds = None
        
    if creds:
        try:
            return build('calendar', 'v3', credentials=creds)
        except Exception as e:
            print(f"[警告] 建立 Google Calendar 服務失敗: {e}")

    print("[警告] 找不到任何可用的 Google API 認證方式 (service_account.json 或 token.json)！")
    return None

def add_event_to_calendar(summary, location, date_str, time_str, description=""):
    """
    date_str: YYYY-MM-DD
    time_str: HH:MM
    """
    service = get_calendar_service()
    if not service:
        print("[警告] Google Calendar 服務不可用，跳過新增至 Google 行事曆。")
        return None

    # Calculate ISO format datetime strings
    start_time_str = f"{date_str}T{time_str}:00"
    start_dt = datetime.datetime.strptime(start_time_str, "%Y-%m-%dT%H:%M:%S")
    # Default event duration to 1 hour
    end_dt = start_dt + datetime.timedelta(hours=1)
    end_time_str = end_dt.strftime("%Y-%m-%dT%H:%M:%S")

    calendar_id = os.getenv("CALENDAR_ID") or 'primary'

    event = {
        'summary': summary,
        'location': location or '',
        'description': description,
        'start': {
            'dateTime': start_time_str,
            'timeZone': 'Asia/Taipei',
        },
        'end': {
            'dateTime': end_time_str,
            'timeZone': 'Asia/Taipei',
        },
    }

    try:
        event_result = service.events().insert(calendarId=calendar_id, body=event).execute()
        print(f"[成功] 行程已同步至 Google 行事曆，連結: {event_result.get('htmlLink')}")
        return event_result.get('id')
    except Exception as e:
        print(f"[錯誤] 新增 Google 行事曆行程時發生錯誤: {e}")
        return None
